### PR TITLE
Add tags API to swagger spec

### PR DESCRIPTION
**Pull request by codenrhoden**
Current spec is missing the /tags resource, and also free-form tags
for nodes.  Add that to the spec, and the corresponding swagger client
code.

Corresponding PR to RackHD/on-http is here: https://github.com/RackHD/on-http/pull/286

### CODE REVIEW

**Comment by kacole2** [comment]
trying to run a test on this but running into issues even getting them to run because of vendoring. this is a trainwreck!

**Comment by kacole2** [comment]
@codenrhoden I'm running `make` but when i try to run the test, i get the following error. anything on your end you did differently?

```
kcoleman-mbp:gorackhd kcoleman$ env DEBUG=1 go test -run TestNodeGetOperation -v
# github.com/emccode/gorackhd
./gorackhd_test.go:30: cannot use transport (type *"github.com/emccode/gorackhd/vendor/github.com/go-swagger/go-swagger/httpkit/client".Runtime) as type runtime.ClientTransport in argument to "github.com/emccode/gorackhd/client".New:
    *"github.com/emccode/gorackhd/vendor/github.com/go-swagger/go-swagger/httpkit/client".Runtime does not implement runtime.ClientTransport (wrong type for Submit method)
        have Submit(*"github.com/emccode/gorackhd/vendor/github.com/go-swagger/go-swagger/client".Operation) (interface {}, error)
        want Submit(*runtime.ClientOperation) (interface {}, error)
./gorackhd_test.go:30: cannot use "github.com/emccode/gorackhd/vendor/github.com/go-swagger/go-swagger/strfmt".Default (type "github.com/emccode/gorackhd/vendor/github.com/go-swagger/go-swagger/strfmt".Registry) as type "github.com/go-openapi/strfmt".Registry in argument to "github.com/emccode/gorackhd/client".New:
    "github.com/emccode/gorackhd/vendor/github.com/go-swagger/go-swagger/strfmt".Registry does not implement "github.com/go-openapi/strfmt".Registry (wrong type for Add method)
        have Add(string, "github.com/emccode/gorackhd/vendor/github.com/go-swagger/go-swagger/strfmt".Format, "github.com/emccode/gorackhd/vendor/github.com/go-swagger/go-swagger/strfmt".Validator) bool
        want Add(string, "github.com/go-openapi/strfmt".Format, "github.com/go-openapi/strfmt".Validator) bool
./gorackhd_test.go:51: cannot use transport (type *"github.com/emccode/gorackhd/vendor/github.com/go-swagger/go-swagger/httpkit/client".Runtime) as type runtime.ClientTransport in argument to "github.com/emccode/gorackhd/client".New:
    *"github.com/emccode/gorackhd/vendor/github.com/go-swagger/go-swagger/httpkit/client".Runtime does not implement runtime.ClientTransport (wrong type for Submit method)
        have Submit(*"github.com/emccode/gorackhd/vendor/github.com/go-swagger/go-swagger/client".Operation) (interface {}, error)
        want Submit(*runtime.ClientOperation) (interface {}, error)
./gorackhd_test.go:51: cannot use "github.com/emccode/gorackhd/vendor/github.com/go-swagger/go-swagger/strfmt".Default (type "github.com/emccode/gorackhd/vendor/github.com/go-swagger/go-swagger/strfmt".Registry) as type "github.com/go-openapi/strfmt".Registry in argument to "github.com/emccode/gorackhd/client".New:
    "github.com/emccode/gorackhd/vendor/github.com/go-swagger/go-swagger/strfmt".Registry does not implement "github.com/go-openapi/strfmt".Registry (wrong type for Add method)
        have Add(string, "github.com/emccode/gorackhd/vendor/github.com/go-swagger/go-swagger/strfmt".Format, "github.com/emccode/gorackhd/vendor/github.com/go-swagger/go-swagger/strfmt".Validator) bool
        want Add(string, "github.com/go-openapi/strfmt".Format, "github.com/go-openapi/strfmt".Validator) bool
./gorackhd_test.go:72: cannot use transport (type *"github.com/emccode/gorackhd/vendor/github.com/go-swagger/go-swagger/httpkit/client".Runtime) as type runtime.ClientTransport in argument to "github.com/emccode/gorackhd/client".New:
    *"github.com/emccode/gorackhd/vendor/github.com/go-swagger/go-swagger/httpkit/client".Runtime does not implement runtime.ClientTransport (wrong type for Submit method)
        have Submit(*"github.com/emccode/gorackhd/vendor/github.com/go-swagger/go-swagger/client".Operation) (interface {}, error)
        want Submit(*runtime.ClientOperation) (interface {}, error)
./gorackhd_test.go:72: cannot use "github.com/emccode/gorackhd/vendor/github.com/go-swagger/go-swagger/strfmt".Default (type "github.com/emccode/gorackhd/vendor/github.com/go-swagger/go-swagger/strfmt".Registry) as type "github.com/go-openapi/strfmt".Registry in argument to "github.com/emccode/gorackhd/client".New:
    "github.com/emccode/gorackhd/vendor/github.com/go-swagger/go-swagger/strfmt".Registry does not implement "github.com/go-openapi/strfmt".Registry (wrong type for Add method)
        have Add(string, "github.com/emccode/gorackhd/vendor/github.com/go-swagger/go-swagger/strfmt".Format, "github.com/emccode/gorackhd/vendor/github.com/go-swagger/go-swagger/strfmt".Validator) bool
        want Add(string, "github.com/go-openapi/strfmt".Format, "github.com/go-openapi/strfmt".Validator) bool
./gorackhd_test.go:112: cannot use transport (type *"github.com/emccode/gorackhd/vendor/github.com/go-swagger/go-swagger/httpkit/client".Runtime) as type runtime.ClientTransport in argument to "github.com/emccode/gorackhd/client".New:
    *"github.com/emccode/gorackhd/vendor/github.com/go-swagger/go-swagger/httpkit/client".Runtime does not implement runtime.ClientTransport (wrong type for Submit method)
        have Submit(*"github.com/emccode/gorackhd/vendor/github.com/go-swagger/go-swagger/client".Operation) (interface {}, error)
        want Submit(*runtime.ClientOperation) (interface {}, error)
./gorackhd_test.go:112: cannot use "github.com/emccode/gorackhd/vendor/github.com/go-swagger/go-swagger/strfmt".Default (type "github.com/emccode/gorackhd/vendor/github.com/go-swagger/go-swagger/strfmt".Registry) as type "github.com/go-openapi/strfmt".Registry in argument to "github.com/emccode/gorackhd/client".New:
    "github.com/emccode/gorackhd/vendor/github.com/go-swagger/go-swagger/strfmt".Registry does not implement "github.com/go-openapi/strfmt".Registry (wrong type for Add method)
        have Add(string, "github.com/emccode/gorackhd/vendor/github.com/go-swagger/go-swagger/strfmt".Format, "github.com/emccode/gorackhd/vendor/github.com/go-swagger/go-swagger/strfmt".Validator) bool
        want Add(string, "github.com/go-openapi/strfmt".Format, "github.com/go-openapi/strfmt".Validator) bool
FAIL    github.com/emccode/gorackhd [build failed]
```

**Comment by codenrhoden** [comment]
@kacole2 I'll look into it!  I get the same thing when I run the same command.

FWIW, Even I checkout the commit right _before_ we added the client/generated code, that fails in the same way.  Not surprising, given the client has nothing to do with vendoring, but just saying that this appears to have been an existing issue.  I'll bisect and see where it started.

**Comment by kacole2** [comment]
LGTM. I think the tests will be fine after merge

**Pull request merged**
