### PR TITLE
Return arrays instead of objects for many GETs

### PR DESCRIPTION
**Pull request by codenrhoden**
Matching PR to RachHD is here: https://github.com/RackHD/on-http/pull/292

Many of the GET schemas are wrong, listing the return as a generic object instead of a list of objects.  Fix that.

Also, remove all the extra whitespace from `monorail.yml` in a separate commit.

**Probably want to merge #15 first**, and then I can rebase this one on top of it. But it can be reviewed as-is.

### CODE REVIEW

**Comment by kacole2** [comment]
i'm looking at this and not sure why this is being changed. What's wrong with the returned object? More parsing?

My main concern is not wanting to keep two different versions of the monorail.yml. One for this and one from the main. The monorail.yml is automatically generated from the RackHD code. Manually editing this will lead to future issues.

**Comment by kacole2** [comment]
If you can get [RackHD/on-http#292](https://github.com/RackHD/on-http/pull/292) merged, I won't hesitate to move this further. But I think that monorail.yml is our "source of truth"

**Comment by codenrhoden** [comment]
I totally agree about the upstream monrail.yml being our source of truth. I'd like them to be identical soon.

I also apologize - I totally missed your PR, https://github.com/RackHD/on-http/pull/175, when I submitted all of mine to RackHD. You had already solved several of the problems I hit.  :(

**Comment by kacole2** [comment]
@codenrhoden same here as #17. anything that needs to be updated before merge since it has been included upstream?

**Comment by codenrhoden** [comment]
@kacole2 this is now good to go as well. Passed the 4 local tests for GET/POST/DELETE/Lookup...

I may do one more PR in the the next few days to re-synch the two monorail.yml files for good, but right now things are looking great!  Thanks for all your help.

**Pull request merged**
