### PR TITLE
Add application/json to swagger spec

### PR DESCRIPTION
**Pull request by codenrhoden**
The swagger spec is missing a media type for "consumes". As it stands
now, if you try to to POST JSON data using the client, the Go code
crashes with a null pointer dereferences. This commit fixes that.

Simple addition to `monorail.yml`. Everything is updated generated code.

### CODE REVIEW

**Comment by kacole2** [comment]
Can you do a quick check to see if the swagger spec in the main RackHD has changed to fit your needs? If it hasn't, I will merge. I just want to keep parity. 

https://github.com/RackHD/on-http/blob/a47e4ebf6c7b77cbe64920808d4b54ee35a504c0/static/monorail.yml

Hasn't been touched in 3 months so I doubt it. I would also consider submitting a PR directly to them as well

**Comment by codenrhoden** [comment]
Oh I do plan to do that.  I need updates to go to both places.  Would you prefer that I do this the other direction? get updates pushed into RackHD first, then pull those down from RackHD?

**Comment by codenrhoden** [comment]
Opened similar PR to RackHD/on-http: https://github.com/RackHD/on-http/pull/281

I have a few more updates to the swagger spec to make.  I can work on getting them in on-http first, as then it will get more eyes about whether the spec has any problems, then do a bigger "synchronize upstream YAML" PR if you like...

**Comment by kacole2** [comment]
no worries on getting them in there first. it would be nice but it may get rejected if 1) breaks one of their tests. 2) their swagger spec is automatically generated.

**Pull request merged**
