### PR TITLE
Update node definition

### PR DESCRIPTION
**Pull request by codenrhoden**
Add missing fields
sku comes back as the ID/string, not as an object.

Here is an example `node` object I get back from the API, to see that it matches:

```
    {
        "autoDiscover": false,
        "catalogs": [],
        "createdAt": "2016-05-18T18:40:30.298Z",
        "id": "573cb71ed11f55c1075ec878",
        "identifiers": [
            "08:00:27:2e:69:a6"
        ],
        "name": "08:00:27:2e:69:a6",
        "obmSettings": [
            {
                "config": {},
                "service": "noop-obm-service"
            }
        ],
        "relations": [
            {
                "relationType": "enclosedBy",
                "targets": [
                    "572434ae23947dd00a5d8533"
                ]
            }
        ],
        "sku": "572516a873b83ec515d32719",
        "tags": [],
        "type": "compute",
        "updatedAt": "2016-05-18T18:41:44.183Z",
        "workflows": []
    }
```

### CODE REVIEW

**Comment by codenrhoden** [comment]
Corresponding RackHD PR: https://github.com/RackHD/on-http/pull/295

**Comment by kacole2** [comment]
@codenrhoden before we keep going down this path, do we know how far along the RackHD 2.0 API is coming along? The end goal is to rip away this monorail.yml file and replace it with the 2.0 version.

**Comment by codenrhoden** [comment]
@kacole2 completely valid question...  I'll ask on Slack.  You had something before about waiting on a 2.0 switchover because they didn't have the `/lookups` endpoint. Was that the only thing holding you back? I can't remember if the 2.0 API is actually official or not yet.

**Comment by codenrhoden** [comment]
The feedback I got on Slack was 2.0 initially out end Q2 (this quarter) and maybe deprecating 1.1 end of this year. So it's a bit away still it seems.

**Comment by kacole2** [comment]
Cool. Will get you squared away soon

**Comment by kacole2** [comment]
i'm more inclined to merge this commit that fixes one small portion for your use case because it will be easier to keep parity when an updated monorail.yml is added for API 2.0. Unlike #16 where it's a pretty big change.

I don't mind the additional  node characteristics, but i would rather keep it as an object because that's what swagger generates. Even though, i wish swagger would generate an array instead.

**Comment by codenrhoden** [comment]
Some changes for this are coming, based on feedback from upstream. Pretty soon we'll get these files to be identical. :)

**Comment by codenrhoden** [comment]
Just an an update -- I have the final changes for this queued up, but need to figure out the `go-swagger` stuff first. This did get pulled into RackHD proper, but had some last minute changes.

**Comment by kacole2** [comment]
@codenrhoden do you need to make any more updates to this PR before we merge since it was accepted to RackHD upstream?

**Comment by codenrhoden** [comment]
The build here is failing because of the same `gopkg.in` stuff that Andrew had pointed out earlier today. However, I also notice that it's doing `make deps`, which it shouldn't be doing anymore. Right now it would be using a version of go-swagger that doesn't work.

**Comment by codenrhoden** [comment]
@kacole2 This is ready to go. Passed local tests. Had to disable `make deps`, but it doesn't do anything useful right now anyways. I generated client code using go-swagger 0.5.9. tip of master currently generates code that doesn't work (this is why I think it's a big deal, and the vendoring solution we have right now does not work as intended).

My solution for that was just go into $GOPATH/src/github.com/go-swagger/go-swagger and then `git checkout 0.5.9`.

**Comment by kacole2** [comment]
baller. thanks dude

**Pull request merged**
